name: steps
on:
  push
jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
      - name: Configuração do node
        uses: actions/setup-node@v3
      - name: verification of node version
        run: node --version
  
